spring:
  application:
    name: service-building
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dormitory?serverTimezone=UTC&characterEncoding=utf-8&userUnicode=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: building
server:
  port: 8085
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
