server:
  port: 9003
spring:
  application:
    name: dormitory-management-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    zookeeper:
#      discovery:
#         register: true
#         enabled: true
#      connect-string: localhost:2181
mybatis:
  mapper-locations:
    - classpath:mapper/**
  type-aliases-package: cn.zust.se.eneity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
feign:
  client:
    default-config: full